# Generated by Django 3.2.25 on 2024-11-29 15:16

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(choices=[(core.models.RoleKey['CK'], 'CK'), (core.models.RoleKey['NL'], 'NL'), (core.models.RoleKey['SA'], 'SA'), (core.models.RoleKey['MANAGER'], 'MANAGER')], max_length=255)),
                ('role_name', models.CharField(choices=[(core.models.RoleName['COOK'], 'COOK'), (core.models.RoleName['NORMAL'], 'NORMAL'), (core.models.RoleName['SUPER_ADMIN'], 'SUPER ADMIN'), (core.models.RoleName['MANAGER'], 'MANAGER')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
