# Generated by Django 3.2.25 on 2024-11-29 15:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='image_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_key',
            field=models.CharField(choices=[(core.models.RoleKey['CK'], 'CK'), (core.models.RoleKey['NL'], 'NL'), (core.models.RoleKey['SA'], 'SA'), (core.models.RoleKey['MANAGER'], 'MANAGER')], default='NL', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[(core.models.RoleName['COOK'], 'COOK'), (core.models.RoleName['NORMAL'], 'NORMAL'), (core.models.RoleName['SUPER_ADMIN'], 'SUPER ADMIN'), (core.models.RoleName['MANAGER'], 'MANAGER')], default='NORMAL', max_length=255),
        ),
    ]
